package com.fintechplatform.api.account.models

enum class AccountLevelStatus {
    LEVEL1_WAITING_CREATION, LEVEL1_CREATED, REQUEST_UPGRADE_TO_LEVEL2, LEVEL2_WAITING_UPGRADE, LEVEL2_UPGRADED, LEVEL2_REFUSED_UPGRADE, REQUEST_UPGRADE_TO_LEVEL3, LEVEL3_WAITING_UPGRADE, LEVEL3_UPGRADED, LEVEL3_REFUSED_UPGRADE
}